Update project documentation and community health files
hashicorp/terraform-provider-vsphere pull request #1529
Opened 2021-12-03 21:30 UTC by tenthirtyam

### Description

**Update community health files**: https://github.com/tenthirtyam/terraform-provider-vsphere/commit/9639c97d997dae4b37e3e988d2f9689682152dd9
- Moves the existing project documentation to the `/docs` directory for better organization **and** to ensure `CONTRIBUTING` and `CODE_OF_CONDUCT` files are discovered by the [GitHub community insights for the project](https://github.com/hashicorp/terraform-provider-vsphere/community).
- Updates the existing project documentation for formatting and readability.

> _"All other supported files may be in the `root` of the repository, the `.github` folder, or the `docs` folder. "_

> NOTE: The project is currently picking up the Code of Conduct from [hashicorp/.github.](https://github.com/hashicorp/.github/blob/master/CODE_OF_CONDUCT.md), which is good. 👍🏻 

**Add installation docs**: https://github.com/tenthirtyam/terraform-provider-vsphere/commit/da94e8ba749347fd86b8cb0bebcc248859709afd
- Adds installation documentation for both automatic and manual methods for macOS, Linux, and Windows.

**Update README.md**: https://github.com/tenthirtyam/terraform-provider-vsphere/commit/848b75554c7b9de949a64b52b983ab4ee6e3e7aa
- Updates the existing `README.md` for context, format, and readability.
- Replaces Google Groups mailing list reference (deprecated) with HashiCorp Discuss (Terraform Providers > Tag: vSphere)
- Updates existing or new links to the new `/docs` directory.

cc @iBrandyJackson and @appilon 

### Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-vsphere/blob/master/CHANGELOG.md):

```release-note
Update of the project documentation and community health files
```
### References

[GitHub Community Health Files](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file)

2022-01-11 20:32 UTC, iBrandyJackson requested changes
hi @tenthirtyam - apologizes for the delay in getting to this - all changes LGTM - could you please rebase and address the conflicts then we can get this merged - thanks!

2022-01-11 21:45 UTC, tenthirtyam commented
Thanks, @iBrandyJackson - I've rebased and addressed the conflict on the FAQ.md.

Ryan

2022-01-12 18:08 UTC, iBrandyJackson approved these changes

2022-01-12 18:15 UTC, merged

2022-01-12 18:43 UTC, tenthirtyam commented
Thank you, @iBrandyJackson!