feat: Add `d/vsphere_compute_cluster_host_group`
hashicorp/terraform-provider-vsphere pull request #1636
Opened 2022-03-24 21:54 UTC by tenthirtyam

### Description

- Adds a datasource for `vsphere_compute_cluster_host_group`.
- Corrects the description for the `name` attribute in `r/vsphere_compute_cluster_host_group`.

### Release Note

`datasoource/compute_cluster_host_group`: New data source can be used to read general attributes of a host group. (GH-xxx)

### References

Closes #1449

### Tests

`main.tf` Example

```hcl
provider "vsphere" {
  vsphere_server       = var.vsphere_server
  user                 = var.vsphere_username
  password             = var.vsphere_password
  allow_unverified_ssl = var.vsphere_insecure
}

data "vsphere_datacenter" "datacenter" {
  name = var.vsphere_datacenter
}

data "vsphere_compute_cluster" "cluster" {
  name          = var.vsphere_cluster
  datacenter_id = data.vsphere_datacenter.datacenter.id
}

data "vsphere_compute_cluster_host_group" "host_group1" {
  name               = "host_group1"
  compute_cluster_id = data.vsphere_compute_cluster.cluster.id
}

resource "vsphere_compute_cluster_vm_host_rule" "host_rule1" {
  compute_cluster_id       = data.vsphere_compute_cluster.cluster.id
  name                     = "terraform-host-rule1"
  vm_group_name            = "vm_group1"
  affinity_host_group_name = data.vsphere_compute_cluster_host_group.host_group1.name
}

output "name" {
  value = data.vsphere_compute_cluster_host_group.host_group1.name
}

output "host_system_ids" {
  value = data.vsphere_compute_cluster_host_group.host_group1.host_system_ids
}
```

```console
❯ terraform apply -auto-approve

Terraform used the selected providers to generate the following execution plan. Resource actions are
indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # vsphere_compute_cluster_vm_host_rule.host_rule1 will be created
  + resource "vsphere_compute_cluster_vm_host_rule" "host_rule1" {
      + affinity_host_group_name = "host_group1"
      + compute_cluster_id       = "domain-c6045"
      + enabled                  = true
      + id                       = (known after apply)
      + name                     = "terraform-host-rule1"
      + vm_group_name            = "vm_group1"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + host_system_ids = [
      + "host-10",
      + "host-64003",
    ]
  + name            = "host_group1"
vsphere_compute_cluster_vm_host_rule.host_rule1: Creating...
vsphere_compute_cluster_vm_host_rule.host_rule1: Creation complete after 0s [id=domain-c6045:405]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

host_system_ids = toset([
  "host-10",
  "host-64003",
])
name = "host_group1"
```

2022-04-08 21:35 UTC, tenthirtyam commented
Marking as a `draft` until I update the pull request to include the supporting documentation.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

2022-04-20 19:14 UTC, appilon requested changes
Aside from the small code changes, can you add docs for the new datasource, I'll add a basic test

2022-05-31 19:49 UTC, tenthirtyam commented on vsphere/data_source_vsphere_compute_cluster_host_group.go
> +	hostSystemIDs := make([]string, 0)
Hi @appilon - The requested updates are now added, successfully tested, and ready for your review.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

2022-05-31 19:49 UTC, tenthirtyam commented on vsphere/data_source_vsphere_compute_cluster_host_group.go
> +	_ = d.Set("host_system_ids", hostSystemIDs)
Hi @appilon - The requested updates are now added, successfully tested, and ready for your review.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

2022-05-31 19:50 UTC, tenthirtyam commented
Hi @appilon,

The requested updates are now added, successfully tested, and ready for your review.

Additionally, the data source docs have been added.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

2022-06-07 23:08 UTC, appilon approved these changes

2022-06-07 23:09 UTC, merged