Add support for role importing
hashicorp/terraform-provider-vsphere pull request #1822
Opened 2023-01-19 17:32 UTC by YoanaStoyanova

### Description

Add support for import of resource_vsphere_role

### Acceptance tests
- [x] Have you added an acceptance test for the functionality being added?
- [x] Have you run the acceptance tests on this branch?

Output from acceptance testing:

```
$ make testacc TESTARGS="-run=TestAccResourceVsphereRole"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccResourceVsphereRole -timeout 240m
?       github.com/hashicorp/terraform-provider-vsphere [no test files]
=== RUN   TestAccResourceVsphereRole_createRole
--- PASS: TestAccResourceVsphereRole_createRole (12.47s)
=== RUN   TestAccResourceVsphereRole_addPrivilege
--- PASS: TestAccResourceVsphereRole_addPrivilege (7.54s)
=== RUN   TestAccResourceVsphereRole_removePrivilege
--- PASS: TestAccResourceVsphereRole_removePrivilege (7.55s)
PASS

```

### Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-vsphere/blob/main/CHANGELOG.md):

```
enhancement:

Makes it possible to import existing vSphere roles to Terraform
```
### References
Closes [#1735 ](https://github.com/hashicorp/terraform-provider-vsphere/issues/1735)

2023-01-19 17:32 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform-provider-vsphere?pullRequest=1822)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform-provider-vsphere?pullRequest=1822)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)


---
**Yoana Stoyanova** seems not to be a GitHub user.
You need a GitHub account to be able to sign the CLA. If you already have a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform-provider-vsphere?pullRequest=1822).</sub>

2023-01-19 17:43 UTC, tenthirtyam reviewed
An update to `website/docs/r/vsphere_role.html.markdown` with the import method should be included.

2023-01-20 14:07 UTC, tenthirtyam commented
> **Note**
> Submitted by Yoana Stoyanova, Member of Technical Staff 2, vSphere Product Engineering at VMware

2023-01-23 14:50 UTC, tenthirtyam requested changes
One very minor docs suggestion.

2023-01-23 14:50 UTC, tenthirtyam commented on website/docs/r/vsphere_role.html.markdown
> +An existing role can be imported into this resource via supplying the role id. An example is below:
```suggestion
An existing role can be imported into this resource by supplying the role id. An example is below:
```

2023-01-23 18:29 UTC, tenthirtyam reviewed
### Test Results: Import of Existing Role

`main.tf`:

```hcl
##################################################################################
# VERSIONS
##################################################################################

terraform {
  required_providers {
    vsphere = {
      source  = "local/hashicorp/vsphere"
      version = ">= 2.3.0"
    }
  }
  required_version = ">= 1.3.6"
}

##################################################################################
# VARIABLES
##################################################################################

# Credentials

variable "vsphere_server" {
  type        = string
  description = "The fully qualified domain name or IP address of the vCenter Server instance. (e.g. sfo-m01-vc01.sfo.rainpole.io)"
}

variable "vsphere_username" {
  type        = string
  description = "The username to login to the vCenter Server instance. (e.g. administrator@vsphere.local)"
  sensitive   = true
}

variable "vsphere_password" {
  type        = string
  description = "The password for the login to the vCenter Server instance."
  sensitive   = true
}

variable "vsphere_insecure" {
  type        = bool
  description = "Set to true for self-signed certificates."
  default     = false
}

# Roles

variable "packer_vsphere_role" {
  type        = string
  description = "The name for the HashiCorp Packer to VMware vSphere custom role."
}

variable "packer_vsphere_privileges" {
  type        = list(string)
  description = "The vSphere privledges for the HashiCorp Packer to VMware vSphere custom role."
}

##################################################################################
# PROVIDERS
##################################################################################

provider "vsphere" {
  vsphere_server       = var.vsphere_server
  user                 = var.vsphere_username
  password             = var.vsphere_password
  allow_unverified_ssl = var.vsphere_insecure
}

##################################################################################
# RESOURCES
##################################################################################

resource "vsphere_role" "packer-vsphere" {
  name            = var.packer_vsphere_role
  role_privileges = var.packer_vsphere_privileges
}


```

`terraform.tfvars`:

```hcl
##################################################################################
# VARIABLES
##################################################################################

# Credentials

vsphere_server   = "m01-vc01.rainpole.io"
vsphere_username = "administrator@vsphere.local"
vsphere_password = "************"
vsphere_insecure = true

# Roles

packer_vsphere_role = "Packer to vSphere Integration Role"

packer_vsphere_privileges = [
  "System.Anonymous",
  "System.Read",
  "System.View",
  "ContentLibrary.AddLibraryItem",
  "ContentLibrary.UpdateLibraryItem",
  "Cryptographer.Access",
  "Cryptographer.Encrypt",
  "Datastore.AllocateSpace",
  "Datastore.Browse",
  "Datastore.FileManagement",
  "Host.Config.SystemManagement",
  "Network.Assign",
  "Resource.AssignVMToPool",
  "VApp.Export",
  "VirtualMachine.Config.AddNewDisk",
  "VirtualMachine.Config.AddRemoveDevice",
  "VirtualMachine.Config.AdvancedConfig",
  "VirtualMachine.Config.Annotation",
  "VirtualMachine.Config.CPUCount",
  "VirtualMachine.Config.EditDevice",
  "VirtualMachine.Config.Memory",
  "VirtualMachine.Config.Resource",
  "VirtualMachine.Config.Settings",
  "VirtualMachine.Interact.DeviceConnection",
  "VirtualMachine.Interact.PowerOff",
  "VirtualMachine.Interact.PowerOn",
  "VirtualMachine.Interact.PutUsbScanCodes",
  "VirtualMachine.Interact.SetCDMedia",
  "VirtualMachine.Interact.SetFloppyMedia",
  "VirtualMachine.Inventory.Create",
  "VirtualMachine.Inventory.CreateFromExisting",
  "VirtualMachine.Inventory.Delete",
  "VirtualMachine.Provisioning.CreateTemplateFromVM",
  "VirtualMachine.Provisioning.MarkAsTemplate",
  "VirtualMachine.Provisioning.MarkAsVM",
  "VirtualMachine.State.CreateSnapshot"
]
```

```console
➜ terraform init                

Initializing the backend...

Initializing provider plugins...
- Finding local/hashicorp/vsphere versions matching ">= 2.3.0"...
- Installing local/hashicorp/vsphere v2.3.0...
- Installed local/hashicorp/vsphere v2.3.0 (unauthenticated)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

╷
│ Warning: Incomplete lock file information for providers
│ 
│ Due to your customized provider installation methods, Terraform was forced to calculate lock file checksums locally for the following providers:
│   - local/hashicorp/vsphere
│ 
│ The current .terraform.lock.hcl file only includes checksums for darwin_amd64, so Terraform running on another platform will fail to install these providers.
│ 
│ To calculate additional checksums for another platform, run:
│   terraform providers lock -platform=linux_amd64
│ (where linux_amd64 is the platform to generate)
╵

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

packer-examples-for-vsphere/terraform/vsphere-role on  v22.12-mac [✘!?] 
➜ terraform import vsphere_role.packer-vsphere 1878255259
vsphere_role.packer-vsphere: Importing from ID "1878255259"...
vsphere_role.packer-vsphere: Import prepared!
  Prepared vsphere_role for import
vsphere_role.packer-vsphere: Refreshing state... [id=1878255259]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

Terraform State:

```hcl
{
  "version": 4,
  "terraform_version": "1.3.7",
  "serial": 1,
  "lineage": "0862efa2-40c0-c31d-f0d1-b14739f2556a",
  "outputs": {},
  "resources": [
    {
      "mode": "managed",
      "type": "vsphere_role",
      "name": "packer-vsphere",
      "provider": "provider[\"local/hashicorp/vsphere\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "1878255259",
            "label": "Packer to vSphere Integration Role",
            "name": "Packer to vSphere Integration Role",
            "role_privileges": [
              "ContentLibrary.AddLibraryItem",
              "ContentLibrary.UpdateLibraryItem",
              "Cryptographer.Access",
              "Cryptographer.Encrypt",
              "Datastore.AllocateSpace",
              "Datastore.Browse",
              "Datastore.FileManagement",
              "Host.Config.SystemManagement",
              "Network.Assign",
              "Resource.AssignVMToPool",
              "VApp.Export",
              "VirtualMachine.Config.AddNewDisk",
              "VirtualMachine.Config.AddRemoveDevice",
              "VirtualMachine.Config.AdvancedConfig",
              "VirtualMachine.Config.Annotation",
              "VirtualMachine.Config.CPUCount",
              "VirtualMachine.Config.EditDevice",
              "VirtualMachine.Config.Memory",
              "VirtualMachine.Config.Resource",
              "VirtualMachine.Config.Settings",
              "VirtualMachine.Interact.DeviceConnection",
              "VirtualMachine.Interact.PowerOff",
              "VirtualMachine.Interact.PowerOn",
              "VirtualMachine.Interact.PutUsbScanCodes",
              "VirtualMachine.Interact.SetCDMedia",
              "VirtualMachine.Interact.SetFloppyMedia",
              "VirtualMachine.Inventory.Create",
              "VirtualMachine.Inventory. [...]

2023-01-23 18:34 UTC, tenthirtyam reviewed
Results for a System Role: Expected

```console
➜ terraform import vsphere_role.no-access -5
vsphere_role.no-access: Importing from ID "-5"...
╷
│ Error: error specified role with id -5 is a system role. System roles are not supported for this operation
```

2023-01-23 18:34 UTC, tenthirtyam approved these changes

2023-02-08 00:48 UTC, appilon approved these changes
I just had to fix the error message in the acctest

2023-02-08 00:52 UTC, merged