Bugfix for issue https://github.com/hashicorp/terraform-provider-vsph…
hashicorp/terraform-provider-vsphere pull request #2009
Opened 2023-08-31 14:33 UTC by nklinkachevAtVMware

Customizing VMs ( customize{} block in the spec) with a hardware version less than 10 fails due to formatting error of the version string passed in the API. Changed the formatting code to format the version to 2 digit integer, left padded with 0 when it's less than 10. That way version 9 becomes vmx-09 instead of vmx-9 and version 10 remains vmx-10.

### Description

Bugfix for issue https://github.com/hashicorp/terraform-provider-vsphere/issues/2005
Changed the formatting code to format the version to 2 digit integer, left padded with 0 when it's less than 10.

### Acceptance tests
- [ ] Have you added an acceptance test for the functionality being added?
- [ ] Have you run the acceptance tests on this branch?

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-vsphere/blob/main/CHANGELOG.md):

```release-note
...
```
### References

2023-08-31 14:33 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform-provider-vsphere?pullRequest=2009)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform-provider-vsphere?pullRequest=2009)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform-provider-vsphere?pullRequest=2009).</sub>

2023-08-31 14:36 UTC, tenthirtyam approved these changes

2023-08-31 14:40 UTC, appilon commented
I will run the VM resource tests on your branch, great job this has been a bug forever

2023-08-31 15:00 UTC, tenthirtyam requested changes
@nklinkachevAtVMware Can you ensure that the commit is signed and that you have signed the CLA?

2023-09-01 16:27 UTC, appilon commented
replacing with #2011 due some unfortunate timeline limitations.

2023-09-01 16:27 UTC, closed without merging