feat: Add data source vgpu profiles
hashicorp/terraform-provider-vsphere pull request #2048
Opened 2023-10-27 18:37 UTC by mristok

### Description

Add a new data source to the provider to query and return available vGPU profiles for a host.

### Acceptance tests
- [ ] Have you added an acceptance test for the functionality being added?
- [ ] Have you run the acceptance tests on this branch?

No acceptance tests added.

### Provider tests
Output from provider testing:

#### ESXi host with A100 GPU
ESXi host with A100 GPU - no vGPU profile name filter
```
Changes to Outputs:
  + all_host_vgpu_profiles = {
      + host_id       = "host-1021"
      + id            = "fdcccc4252c0516e9d54a1ee6e851ba9f336c64502d6e80c5a684072f6e02bdc"
      + name          = null
      + vgpu_profiles = [
          + {
              + disk_snapshot_supported   = true
              + memory_snapshot_supported = true
              + migrate_supported         = true
              + suspend_supported         = true
              + vgpu                      = "grid_a100d-4c"
            },
          + {
              + disk_snapshot_supported   = true
              + memory_snapshot_supported = true
              + migrate_supported         = true
              + suspend_supported         = true
              + vgpu                      = "grid_a100d-8c"
            },
          + {
              + disk_snapshot_supported   = true
              + memory_snapshot_supported = true
              + migrate_supported         = true
              + suspend_supported         = true
              + vgpu                      = "grid_a100d-10c"
            },
          + {
              + disk_snapshot_supported   = true
              + memory_snapshot_supported = true
              + migrate_supported         = true
              + suspend_supported         = true
              + vgpu                      = "grid_a100d-16c"
            },
          + {
              + disk_snapshot_supported   = true
              + memory_snapshot_supported = true
              + migrate_supported         = true
              + suspend_supported         = true
              + vgpu                      = "grid_a100d-20c"
            },
          + {
              + disk_snapshot_supported   = true
              + memory_snapshot_supported = true
              + migrate_supported         = true
              + suspend_supported         = true
              + vgpu                      = "grid_a100d-40c"
            },
          + {
              + disk_snapshot_supported   = true
              + memory_snapshot_supported = true
              + migrate_supported         = true
              + suspend_supported         = true
              + vgpu                      = "grid_a100d-80c"
            },
        ]
    }
```

ESXi host with A100 GPU - vGPU profile name filter `grid_a100d-80c`
```
Changes to Outputs:
  + single_host_vgpu_profile = {
      + host_id       = "host-1021"
      + id            = "fdcccc4252c0516e9d54a1ee6e851ba9f336c64502d6e80c5a684072f6e02bdc"
      + name          = "grid_a100d-80c"
      + vgpu_profiles = [
          + {
              + disk_snapshot_supported   = true
              + memory_snapshot_supported = true
              + migrate_supported         = true
              + suspend_supported         = true
              + vgpu                      = "grid_a100d-80c"
            },
        ]
    }
```

#### ESXi host without GPU
ESXi host without GPU - no vGPU profile name filter
```
Changes to Outputs:
  + all_host_vgpu_profiles = {
      + host_id       = "host-4016"
      + id            = "7025a70fb666db1fd6f2f0d3f27ca9c6cb574a780443fd37d49685275e5b9b66"
      + name          = null
      + vgpu_profiles = []
    }
```

ESXi host without GPU - vGPU profile name filter `grid_a100d-80c`
```
Changes to Outputs:
  + single_host_vgpu_profiles = {
      + host_id       = "host-4016"
      + id            = "7025a70fb666db1fd6f2f0d3f27ca9c6cb574a780443fd37d49685275e5b9b66"
      + name          = "grid_a100d-80c"
      + vgpu_profiles = []
    }
```

### Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-vsphere/blob/main/CHANGELOG.md):

```release-note
...
```
### References

#2047

2023-10-27 18:37 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform-provider-vsphere?pullRequest=2048)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform-provider-vsphere?pullRequest=2048)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform-provider-vsphere?pullRequest=2048).</sub>

2023-10-27 18:48 UTC, tenthirtyam commented
The markdown for the data source docs should also be included.

2023-10-30 07:50 UTC, vasilsatanasov requested changes
Hi @mristok this is a great augmentation to the provider but I think that this data should be part of the `vsphere_host ` data source. This will make it more consistent for the users as they will have to write less HCL code. I also do not see an acceptance test for this functionality and this will be a very good addition to the PR.

Best regards, Vasil

2023-10-30 19:13 UTC, mristok commented
@vasilsatanasov This functionality can be moved into the `vsphere_host` data source; the reason I made it separate was so that it was aligned with the `vsphere_host_pci_device` being a separate data source.

Also, I did not add any acceptance tests to this given that the GPU based hardware in Equinix Metal is expensive (and based on 12/36 month contracts). If this were to be added to the acceptance tests would the following be in line with your vision:
  - User must specify a GPU ESXi host (not part of the standard acceptance test deployment)
    - Example: `TF_VAR_VSPHERE_TEST_GPU_ESXI`
  - If no GPU ESXi host is specified, the test is skipped

2023-11-09 08:32 UTC, vasilsatanasov approved these changes
LGTM!

2023-11-09 11:11 UTC, tenthirtyam approved these changes
lgtm

2024-02-12 17:01 UTC, merged