docs: `vsphere_virtual_machine` updated disks info
hashicorp/terraform-provider-vsphere pull request #2272
Opened 2024-10-02 16:38 UTC by burnsjared0415

### Description
`resource/vsphere_virtual_machine`: Updates to fix examples of `disk0` to reflect that during import the disk get set back to default like `Hard Disk 1`.

### Acceptance tests

- [ ] Have you added an acceptance test for the functionality being added?
- [ ] Have you run the acceptance tests on this branch?

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### Release Note

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-vsphere/blob/main/CHANGELOG.md):

```release-note
...
```

### References
Closes #2199

2024-10-02 16:46 UTC, tenthirtyam commented on website/docs/r/virtual_machine.html.markdown
> +~> **NOTE:** Any custom `label` set at deployment of machine through terraform, on import will  not have custom `label`, it will default back to `Hard Disk x`.
```suggestion
~> **NOTE:** Any custom `label` set at deployment of machine through Terraform, on import will not have the custom `label` and will default to `Hard Disk _x_`.
```

2024-10-02 16:50 UTC, tenthirtyam requested changes
Minor suggestion.

2024-10-02 17:43 UTC, tenthirtyam approved these changes
LGTM

2024-10-08 15:36 UTC, appilon approved these changes

2024-10-08 16:45 UTC, merged